[package]
name = "hello-rocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
sqlx = { version = "0.5", features = [ "runtime-actix-native-tls","mysql" ] }
anyhow = "1.0"